name: "Validate HTML"

on:
  pull_request:
    types: [opened]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@<latest version>
      with:
        root: /
        format: text
        css: true